/**
 * Photographic asset registry — GENERATED by scripts/fetch-images.mjs
 * (run via the manual "fetch-images" GitHub Action). Until that runs,
 * every entry is null and the UI falls back to the two-ink SVG art.
 *
 * Do not edit by hand: the fetch workflow overwrites this file with the
 * public-domain images it downloaded, duotone-prepped, and committed,
 * mapping ids -> paths under public/img/. Missing/license-rejected
 * entries stay null (permanent SVG fallback).
 */
import type { FactionId } from '../engine/factions';
import type { UnitId } from '../engine/loyalty';

/** relative path under the site base, or null if no cleared photo exists. */
export const PORTRAIT_PATHS: Record<FactionId, string | null> = {
  moderates: null,
  hardliners: null,
  labor: null,
  students: null,
};

export const UNIT_PATHS: Record<UnitId, string | null> = {
  garrison: null,
  police: null,
  guard: null,
};

/** Keyed by event card id (see src/content/events/*). */
export const EVENT_PATHS: Record<string, string | null> = {};

export const HERO_PATH: string | null = null;
